// webapp/src/sections/game.detail/GameDetail.tsx
import React, { useState, useEffect } from 'react';
import { NavLink, useParams } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import LinksList from '../../components/links.list/LinksList';

function GameDetail() {
    let { id } = useParams();
    let [gameData, setGameData] = useState<any>(null);

    useEffect(() => {
        try {
            const data: any = require(`../../db/games/${id}.json`);
            setGameData(data);
        } catch {
            setGameData(null);
        }
    }, [id]);

    const renderLinkWithoutAuthor = (resource: any) => {
        if (resource.href) {
            return (<span><a href={ resource.href }>{ resource.name }</a></span>);
        } else {
            return (<span>{ resource.name }</span>);
        }
    };

    return (
        <div className="row">
            {gameData ?
                <div>
                    <h1>{ gameData.title }</h1>
                    <div className="game-img"><img src={gameData.img} alt={`Captura de pantalla del juego '${gameData.title}'`} /></div>
                    <ReactMarkdown source={gameData.summary}/>

                    {gameData.background && <section>
                        <h2>Trasfondo</h2>
                        <ReactMarkdown source={gameData.background} />
                    </section>}

                    {gameData.mechanics && <section>
                        <h2>Mecánicas</h2>
                        <ReactMarkdown source={gameData.mechanics} />
                    </section>}

                    {gameData.controls && <section>
                        <h2>Controles</h2>
                        <ul>
                            {gameData.controls.map((control: any, index: number) => (
                                <li key={index}>{ control.key }: { control.meaning }</li>
                            ))}
                        </ul>
                    </section>}

                    <h2>Créditos</h2>
                    {gameData.credits.own.map((credits: any, index: number) => (
                        <section key={index}>
                            <h3>{ credits.title }</h3>
                            <ul>
                                {credits.people.map((person: any, index: number) => (
                                    <li key={index}>{ person }</li>
                                ))}
                            </ul>
                        </section>
                    ))}

                    {gameData.credits['third-party'] && <section>
                        <h2>Trabajo de terceros</h2>
                        {gameData.credits['third-party'].map((credits: any, index: number) => (
                            <section key={index}>
                                <h3>{ credits.title }</h3>
                                {credits.body && <ReactMarkdown source={credits.body} />}
                                {credits.resources && <ul>
                                    {credits.resources.map((resource: any, index: number) => (
                                        <li key={index}>
                                            { resource.author ?
                                                <span>"{ resource.name }" - { resource.author }</span>
                                                : renderLinkWithoutAuthor(resource)
                                            }
                                        </li>
                                    ))}
                                </ul>}
                            </section>
                        ))}
                    </section>}

                    {gameData.credits.thanks && <section>
                        <h2>Agradecimientos</h2>
                        <ul>
                            {gameData.credits.thanks.map((thanks: any, index: number) => (
                                <li key={index}>{ thanks }</li>
                            ))}
                        </ul>
                    </section>}

                    <h2>Enlaces y descargas</h2>
                    <LinksList links={gameData.links} />
                </div>
                : <div>
                    <p>El videojuego buscado no existe o no pudo ser cargado.</p>
                    <p><NavLink to="/games">Volver a la lista de videojuegos</NavLink></p>
                </div>
            }
        </div>
    );
}

export default GameDetail;

// webapp/src/app/sections/game-detail/game-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { ProjectLoader } from '../../services/project-loader/project-loader.service';

@Component({
  selector: 'app-game-detail',
  templateUrl: './game-detail.component.html',
  styleUrls: ['./game-detail.component.css']
})
export class GameDetailComponent implements OnInit {

    public gameData : any;

    constructor(private route: ActivatedRoute, private projectLoader: ProjectLoader) {
        const id = this.route.snapshot.paramMap.get('id');
        this.projectLoader.loadProjectData('./assets/db/games/' + id + '.json').then(gameData => {
            this.gameData = gameData;
        });
    }

    ngOnInit() {
    }

}

<div *ngIf="gameData">
    <h1>{{ gameData.title }}</h1>
    <div class="game-img"><img [src]=gameData.img /></div>
    <p><markdown [data]="gameData.summary"></markdown></p>

    <section *ngIf="gameData.background">
        <h2>Trasfondo</h2>
        <p><markdown [data]="gameData.background"></markdown></p>
    </section>

    <section *ngIf="gameData.mechanics">
        <h2>Mecánicas</h2>
        <p><markdown [data]="gameData.mechanics"></markdown></p>
    </section>

    <section *ngIf="gameData.controls">
        <h2>Controles</h2>
        <ul>
            <li *ngFor="let control of gameData.controls">{{ control.key }}: {{ control.meaning }}</li>
        </ul>
    </section>

    <h2>Créditos</h2>
    <section *ngFor="let credits of gameData.credits.own">
        <h3>{{ credits.title }}</h3>
        <ul>
            <li *ngFor="let person of credits.people">{{ person }}</li>
        </ul>
    </section>

    <section *ngIf="gameData.credits['third-party']">
        <h2>Trabajo de terceros</h2>
        <section *ngFor="let credits of gameData.credits['third-party']">
            <h3>{{ credits.title }}</h3>
            <p *ngIf="credits.body"><markdown [data]="credits.body"></markdown></p>
            <ul>
                <li *ngFor="let resource of credits.resources">
                    <span *ngIf="resource.author">"{{ resource.name }}" - {{ resource.author }}</span>
                    <span *ngIf="!resource.author && resource.href"><a href="{{ resource.href }}">{{ resource.name }}</a></span>
                    <span *ngIf="!resource.author && !resource.href">{{ resource.name }}</span>
                </li>
            </ul>
        </section>
    </section>

    <section *ngIf="gameData.credits.thanks">
        <h2>Agradecimientos</h2>
        <ul>
            <li *ngFor="let thanks of gameData.credits.thanks">{{ thanks }}</li>
        </ul>
    </section>

    <h2>Enlaces y descargas</h2>
    <app-links-list [links]="gameData.links"></app-links-list>
</div>
<div *ngIf="!gameData">
    <p>El videojuego buscado no existe o no pudo ser cargado.</p>
    <p><a routerLink="/games">Volver a la lista de videojuegos</a></p>
</div>
