// webapp/src/app/sections/software-detail/software-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import {BrowserModule, DomSanitizer} from '@angular/platform-browser'
import { ProjectLoader } from '../../services/project-loader/project-loader.service';

@Component({
  selector: 'app-software-detail',
  templateUrl: './software-detail.component.html',
  styleUrls: ['./software-detail.component.css']
})
export class SoftwareDetailComponent implements OnInit {

  public softwareData: any;

  constructor(private route: ActivatedRoute, private sanitizer: DomSanitizer, private projectLoader: ProjectLoader) { }

  ngOnInit() {
     const id = this.route.snapshot.paramMap.get('id');
     this.projectLoader.loadProjectData('./assets/db/software/' + id + '.json').then(softwareData => {
        this.softwareData = softwareData;
     });
  }

}

<div *ngIf="softwareData">
    <h1>{{ softwareData.title }}</h1>
    <img [src]=softwareData.img />
    <p><markdown [data]="softwareData.summary"></markdown></p>

    <section *ngIf="softwareData.multimedia">
        <h2>Multimedia</h2>
        <iframe *ngFor="let video of softwareData.multimedia.videos" width="560" height="315" [src]="sanitizer.bypassSecurityTrustResourceUrl(video)" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </section>
    <section *ngIf="softwareData.links">
        <h2>Enlaces y descargas</h2>
        <app-links-list [links]="softwareData.links"></app-links-list>
    </section>
</div>
<div *ngIf="!softwareData">
    <p>El software buscado no existe o no pudo ser cargado.</p>
    <p><a routerLink="/software">Volver a la lista de software</a></p>
</div>

// webapp/src/sections/software.detail/SoftwareDetail.tsx
import React, { useState, useEffect } from 'react';
import { NavLink, useParams } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import LinksList from '../../components/links.list/LinksList';

function SoftwareDetail() {
    let { id } = useParams();
    let [softwareData, setSoftwareData] = useState<any>(null);

    useEffect(() => {
        try {
            const data: any = require(`../../db/software/${id}.json`);
            setSoftwareData(data);
        } catch {
            setSoftwareData(null);
        }
    }, [id]);

    return (
        <div className="row">
            {softwareData ?
                <div>
                    <h1>{ softwareData.title }</h1>
                    <img src={softwareData.img} alt={`Captura de pantalla de '${softwareData.title}'`} />
                    <ReactMarkdown source={softwareData.summary} />

                    {softwareData.multimedia && <section>
                        <h2>Multimedia</h2>
                        {softwareData.multimedia.videos.map((video: any, index: number) => (
                            <iframe key={index} title={''+index} width="560" height="315" src={video} frameBorder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
                        ))};
                    </section>}

                    {softwareData.links && <section>
                        <h2>Enlaces y descargas</h2>
                        <LinksList links={softwareData.links} />
                    </section>}
                </div>
                : <div>
                    <p>El software buscado no existe o no pudo ser cargado.</p>
                    <p><NavLink to="/software">Volver a la lista de software</NavLink></p>
                </div>
            }
        </div>
    );
}

export default SoftwareDetail;
