// webapp/src/app/lib/links-list/links-list.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-links-list',
  templateUrl: './links-list.component.html',
  styleUrls: ['./links-list.component.css']
})
export class LinksListComponent implements OnInit {
  @Input() public links: any;

  constructor() { }

  ngOnInit() {
  }

}

<ul>
    <li *ngFor="let link of links">
	<a *ngIf="link.href.startsWith('http')" target="_blank" [href]="link.href">{{ link.text }}</a>
        <a *ngIf="!link.href.startsWith('http')" [href]="link.href">{{ link.text }}</a>

        <span *ngIf="link.warning"> ({{ link.warning }})</span>
    </li>
</ul>

// webapp/src/components/links.list/LinksList.tsx
import React from 'react';
import './LinksList.css';

function LinksList(props: any) {
    let {links} = props;
    return (
        <ul>
            {links.map((link: any, index: number) => (
                <li key={index}>
                    {link.href.startsWith('http') ?
                        <a target="_blank" rel="noopener noreferrer" href={ link.href }>{ link.text }</a>
                        : <span>
                            <a rel="noopener noreferrer" className={`${link.href.indexOf('/play') !== -1 ? 'play-online-link' : ''}`} href={link.href}>{ link.text }</a>
                          </span>
                    }
                    {link.warning && <span> ({ link.warning })</span>}
                </li>
            ))}
        </ul>
    );
};

export default LinksList;
